# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4194ee152eac7ca2f920651102106a6a09ca63dae1b92bf79366a6f1d9d326b8ebcac3588761f0b5fb06dd5c16faa1b1e32ad52c36bf237f9a6c6845b3ac4266

test:
  secret_key_base: 1795b2c57cc8e283f3809cd1f8ff15b82583aade5a118752ff7a25877ab1e635aecd264d88127150537c7eacce41244225736202530df8938cee15091c419599

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
